dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
  - '9'
services:
  - mysql
before_install:
  - bash .travis.install-mysql-5.7.sh
install:
  - npm i -g egg-born
  - egg-born test-full-stack --type="front-backend-mysql" --silent
  - cd test-full-stack
  - npm i
script:
  - npm run build:front
  - npm run cov:backend
  - cd $(npm config get prefix)/lib/node_modules/egg-born/test
  - npm i
  - npm run cov:backend
after_script:
  - npm i codecov -g && codecov
