# todo: 
sudo: false
language: node_js
node_js:
  - '7'
matrix:
  include:
    - node_js: '8'
      env: 'NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly'
  allow_failures:
    # Allow the nightly installs to fail
    - env: 'NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly'
install:
  - cd backend && npm i && cd ..
script:
  - npm run b-ci
after_script:
  - npm i codecov -g && codecov
